[versions]
android-gradle = "8.13.1"
kotlin-gradle = "2.2.21"
ktlint = "1.8.0"
maven-publish = "0.35.0"
spotless = "8.0.0"
tapmoc = "0.1.0"

[libraries]
injekt = { module = "com.github.mihonapp:injekt", version = "91edab2317" }
jsoup = { module = "org.jsoup:jsoup", version = "1.21.2" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.3.0" }
rxandroid = { module = "io.reactivex:rxandroid", version = "1.2.1" }
rxjava = { module = "io.reactivex:rxjava", version = "1.3.8" }

ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-gradle" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
tapmoc = { id = "com.gradleup.compat.patrouille", version.ref = "tapmoc" }
